In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\Sıla\\Downloads\\adult\\adult.data", header=None)

In [3]:
data

0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      10  11  12  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   13      14  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [4]:
data.values

array([[39, ' State-gov', 77516, ..., 40, ' United-States', ' <=50K'],
       [50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [5]:
columns = ['Age',
    'Workclass',
    'fnlwgt',
    'Education',
    'education-num',
    'Marital Status',
    'Occupation',
    'Relationship',
    'Race',
    'Sex',
    'Capital Gain',
    'Capital Loss',
    'Hours per week',
    'Country',
    'class']

In [6]:
adult_data = pd.DataFrame(data=data.values, columns=columns)

In [7]:
adult_data.head()

Age          Workclass  fnlwgt   Education education-num  \
0  39          State-gov   77516   Bachelors            13   
1  50   Self-emp-not-inc   83311   Bachelors            13   
2  38            Private  215646     HS-grad             9   
3  53            Private  234721        11th             7   
4  28            Private  338409   Bachelors            13   

        Marital Status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

  Capital Gain Capital Loss Hours per week         Country   class  
0         2174            0             40   United-States   <=50K  
1            0            0             13   United-States   <=50K  
2            0            0             40   United-States   <=50K  
3            0            0             40   United-States   <=50K  
4            0            0             40            Cuba   <=50K

In [8]:
adult_data.columns

Index(['Age', 'Workclass', 'fnlwgt', 'Education', 'education-num',
       'Marital Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital Gain', 'Capital Loss', 'Hours per week', 'Country', 'class'],
      dtype='object')

In [9]:
categorical_columns=['Workclass',
 'Education',
 'Marital Status',
 'Occupation',
 'Relationship',
 'Race',
 'Sex',
 'Country']

In [10]:
adult_data['Education'].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [11]:
for x in categorical_columns:
    adult_data[x] = adult_data[x].str.strip() 
# adult_data['Workclass'] = adult_data["Workclass"].str.strip()
# adult_data['Education'] = adult_data["Education"].str.strip()
# adult_data['Marital Status'] = adult_data["Marital Status"].str.strip()
# adult_data['Occupation'] = adult_data["Occupation"].str.strip()
# adult_data['Relationship'] = adult_data["Relationship"].str.strip()
# adult_data['Race'] = adult_data["Race"].str.strip()
# adult_data['Sex'] = adult_data["Sex"].str.strip()
# adult_data['Country'] = adult_data["Country"].str.strip()
# adult_data['class'] = adult_data["class"].str.strip()

In [12]:
adult_data['Education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [13]:
numerical_columns = ['Age', 'Capital Gain', 'Capital Loss', 'Hours per week']

In [14]:
# define low education
low_education = [
    '11th',
    '9th',
    'Some-college',
    'Assoc-acdm',
    'Assoc-voc', 
    '7th-8th',
    '5th-6th', 
    '10th', 
    '1st-4th', 
    'Preschool', 
    '12th',
    'HS-grad',
    'Bachelors'

]
# define high education
high_education = [
    'Bachelors',
    'Masters',
    'Doctorate',
    'Prof-school'
]
print("Low education:", low_education)
print("High education:", high_education)

Low education: ['11th', '9th', 'Some-college', 'Assoc-acdm', 'Assoc-voc', '7th-8th', '5th-6th', '10th', '1st-4th', 'Preschool', '12th', 'HS-grad', 'Bachelors']
High education: ['Bachelors', 'Masters', 'Doctorate', 'Prof-school']


In [15]:
low_education

['11th',
 '9th',
 'Some-college',
 'Assoc-acdm',
 'Assoc-voc',
 '7th-8th',
 '5th-6th',
 '10th',
 '1st-4th',
 'Preschool',
 '12th',
 'HS-grad',
 'Bachelors']

In [16]:
# select instances for low and high education
low_education_mask = pd.Series(adult_data.loc[:, "Education"]).isin(low_education).to_numpy()
high_education_mask = pd.Series(adult_data.loc[:, "Education"]).isin(high_education).to_numpy()

In [17]:
low_education_mask

array([ True,  True,  True, ...,  True,  True,  True])

In [18]:
high_education_mask

array([ True,  True, False, ..., False, False, False])

In [19]:
X_low, X_high = adult_data.values[low_education_mask], adult_data.values[high_education_mask]

In [20]:
X_low

array([[39, 'State-gov', 77516, ..., 40, 'United-States', ' <=50K'],
       [50, 'Self-emp-not-inc', 83311, ..., 13, 'United-States',
        ' <=50K'],
       [38, 'Private', 215646, ..., 40, 'United-States', ' <=50K'],
       ...,
       [58, 'Private', 151910, ..., 40, 'United-States', ' <=50K'],
       [22, 'Private', 201490, ..., 20, 'United-States', ' <=50K'],
       [52, 'Self-emp-inc', 287927, ..., 40, 'United-States', ' >50K']],
      dtype=object)

In [21]:
X_low.shape

(29849, 15)

In [22]:
X_high.shape

(8067, 15)

In [23]:
import numpy as np
from sklearn.model_selection import train_test_split

In [24]:
size = 1000
np.random.seed(0)

# define reference and H0 dataset
idx_low = np.random.choice(np.arange(X_low.shape[0]), size=2*size, replace=False)
x_ref, x_h0 = train_test_split(X_low[idx_low], test_size=0.5, random_state=5, shuffle=True)

# define reference and H1 dataset
idx_high = np.random.choice(np.arange(X_high.shape[0]), size=size, replace=False)
x_h1 = X_high[idx_high]

In [25]:
categorical_ids = [adult_data.columns.get_loc(x) for x in categorical_columns]
numerical_ids = [adult_data.columns.get_loc(x) for x in numerical_columns]

In [26]:
categorical_ids

[1, 3, 5, 6, 7, 8, 9, 13]

In [27]:
adult_data.head()

Age         Workclass  fnlwgt  Education education-num      Marital Status  \
0  39         State-gov   77516  Bachelors            13       Never-married   
1  50  Self-emp-not-inc   83311  Bachelors            13  Married-civ-spouse   
2  38           Private  215646    HS-grad             9            Divorced   
3  53           Private  234721       11th             7  Married-civ-spouse   
4  28           Private  338409  Bachelors            13  Married-civ-spouse   

          Occupation   Relationship   Race     Sex Capital Gain Capital Loss  \
0       Adm-clerical  Not-in-family  White    Male         2174            0   
1    Exec-managerial        Husband  White    Male            0            0   
2  Handlers-cleaners  Not-in-family  White    Male            0            0   
3  Handlers-cleaners        Husband  Black    Male            0            0   
4     Prof-specialty           Wife  Black  Female            0            0   

  Hours per week        Country   class  
0             40  United-States   <=50K  
1             13  United-States   <=50K  
2             40  United-States   <=50K  
3             40  United-States   <=50K  
4             40           Cuba   <=50K

Column Transformer

In [28]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [29]:
[range(len(i)) for i in [list(adult_data[x].unique()) for x in categorical_columns]]

[range(0, 9),
 range(0, 16),
 range(0, 7),
 range(0, 15),
 range(0, 6),
 range(0, 5),
 range(0, 2),
 range(0, 42)]

In [30]:
# define numerical standard scaler.
num_transf = StandardScaler()

# define categorical one-hot encoder.
cat_transf = OneHotEncoder(
    categories=[range(len(i)) for i in [list(adult_data[x].unique()) for x in categorical_columns]],
    handle_unknown="ignore"
)

# Define column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", cat_transf, categorical_ids),
        ("num", num_transf, numerical_ids),
    ],
    sparse_threshold=0
)

# fit preprocessor.
preprocessor = preprocessor.fit(np.concatenate([x_ref, x_h0, x_h1]))

Defining the Classifier Drift Detector

In [31]:
from alibi_detect.cd import ClassifierDrift

c:\users\sıla\appdata\local\programs\python\python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
# define classifier
model = RandomForestClassifier()

# define drift detector with binarize prediction
cd = ClassifierDrift(
    x_ref=x_ref,
    model=model,
    backend='sklearn',
    preprocess_fn=preprocessor.transform,
    binarize_preds=True,
    n_folds=2,
)

Both `n_folds` and `train_size` specified. By default `n_folds` is used.
`retrain_from_scratch=True` sets automatically the parameter `warm_start=False`.
`use_oob=False` sets automatically the classifier parameters `oob_score=False`.


In [36]:
cd.predict(x=x_h0)

{'data': {'is_drift': 0,
  'distance': 0,
  'p_val': 0.9849708380487369,
  'threshold': 0.05,
  'probs_ref': array([0.51504167, 0.65      , 0.70463736, 0.47533333, 0.608     ,
         0.45480965, 0.855     , 0.90811111, 0.31652381, 0.33938095,
         0.82      , 0.69      , 0.72      , 0.575     , 0.74991017,
         0.71714286, 0.7196774 , 0.37184594, 0.59661984, 0.7975    ,
         0.10509091, 0.74446522, 0.44854149, 0.60414538, 0.64908333,
         0.62759224, 0.37184594, 0.49317116, 0.6291909 , 0.4       ,
         0.989     , 0.94428788, 0.47      , 0.49526125, 0.13515865,
         0.45371744, 0.08      , 0.2420119 , 0.63416667, 0.54168133,
         0.20799808, 0.55181721, 0.49091156, 0.516     , 0.5323923 ,
         0.2       , 0.26471355, 0.43      , 0.57391883, 0.62759224,
         0.54333333, 0.99      , 0.51333333, 0.28120646, 0.215     ,
         0.51833333, 0.41685048, 0.40099723, 0.70197235, 0.37184594,
         0.60502438, 0.63054762, 0.47972766, 0.44269048, 0.2925  

In [37]:
labels = ['No!', 'Yes!']

def print_preds(preds: dict, used_data_name: str) -> None:
    print(used_data_name)
    print('Drift? {}'.format(labels[preds['data']['is_drift']]))
    print(f'p-value: {preds["data"]["p_val"]:.3f}')
    print('')

In [38]:
print_preds(cd.predict(x=x_h0), "H0")

H0
Drift? No!
p-value: 0.873



In [39]:
cd.predict(x=x_h1)

{'data': {'is_drift': 1,
  'distance': 0.09000000000000008,
  'p_val': 3.099903904699595e-05,
  'threshold': 0.05,
  'probs_ref': array([0.73236364, 0.88      , 0.74200649, 0.01      , 0.14      ,
         0.18542116, 0.97      , 0.96      , 0.16      , 0.04      ,
         0.82      , 0.43      , 0.26      , 0.69135317, 0.4325    ,
         0.66      , 0.41346828, 0.32080046, 0.28388095, 0.8       ,
         0.328     , 0.69464503, 0.45391538, 0.483     , 0.66988889,
         0.60600414, 0.32080046, 0.37141703, 0.55566722, 0.26833333,
         1.        , 0.925     , 0.16      , 0.84      , 0.33983405,
         0.38256333, 0.42486275, 0.39739214, 0.98      , 0.30098697,
         0.41859419, 0.24752463, 0.59465163, 0.235     , 0.33774482,
         0.71      , 0.17974324, 0.90983333, 0.56257726, 0.60600414,
         0.24666667, 0.01      , 0.13583333, 0.41676446, 0.43916667,
         0.73614286, 0.73639995, 0.45755508, 0.50515615, 0.32080046,
         0.41023499, 0.51833333, 0.32664427,

In [40]:
print_preds(cd.predict(x=x_h1), "H1")

H1
Drift? Yes!
p-value: 0.000



Saving and Loading the detector

In [41]:
from alibi_detect.saving import save_detector, load_detector

In [42]:
save_detector(cd, './detectors5')

Directory detectors5 does not exist and is now created.
Directory detectors5\preprocess_fn does not exist and is now created.
Directory detectors5\model does not exist and is now created.


In [43]:
cdl = load_detector('./detectors5/')

Both `n_folds` and `train_size` specified. By default `n_folds` is used.
`retrain_from_scratch=True` sets automatically the parameter `warm_start=False`.
`use_oob=False` sets automatically the classifier parameters `oob_score=False`.


In [44]:
print_preds(cdl.predict(x=x_h1), "H1")

H1
Drift? Yes!
p-value: 0.000

